spring.application.name=financial-assets
server.port=8080

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/financial_assets}
stooq.api.key=${STOOQ_API_KEY:}

alpha.vantage.api.key=${ALPHA_VANTAGE_API_KEY:demo}
